[package]
edition = "2021"
name = "nenobi"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
instant = {version = "0.1.12", features = ["wasm-bindgen"]}
num-traits = "0.2.19"

[dev-dependencies]
image = "0.25"
