version: '3.8'

volumes:
  postgres-data:

services:
  app:
    image: ghcr.io/mitoma/sandbox-dev:latest@sha256:f824ea442b3da278830b34b4c44657636bbb99b150386a2e0f3a9dfbb49678ee
    volumes:
      - ..:/workspace:cached
      - ~/.cargo/registry:/home/mitoma/.cargo/registry:cached
      - ~/.cargo/git:/home/mitoma/.cargo/git:cached
      - ~/.npm:/home/mitoma/.npm:cached
      - ~/.config/gcloud:/home/mitoma/.config/gcloud:cached
      - ~/.docker:/home/mitoma/.docker:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
