version: '3.8'

volumes:
  postgres-data:

services:
  app:
    image: ghcr.io/mitoma/sandbox-dev:latest@sha256:36fdfdd0e7bb0a1a029f4be0ea04c880d9c19c8690d1a4d59ccf1682c71835ef
    volumes:
      - ..:/workspace:cached
      - ~/.cargo/registry:/home/mitoma/.cargo/registry:cached
      - ~/.cargo/git:/home/mitoma/.cargo/git:cached
      - ~/.npm:/home/mitoma/.npm:cached
      - ~/.config/gcloud:/home/mitoma/.config/gcloud:cached
      - ~/.docker:/home/mitoma/.docker:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
