version: '3.8'

volumes:
  postgres-data:

services:
  app:
    image: ghcr.io/mitoma/sandbox-dev:latest@sha256:fe37354ecb8fd4ac944d0ad5b68c1711d353dc98832b54d3b2afebe110d69928
    volumes:
      - ..:/workspace:cached
      - ~/.cargo/registry:/home/mitoma/.cargo/registry:cached
      - ~/.cargo/git:/home/mitoma/.cargo/git:cached
      - ~/.npm:/home/mitoma/.npm:cached
      - ~/.config/gcloud:/home/mitoma/.config/gcloud:cached
      - ~/.docker:/home/mitoma/.docker:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
