name: Continuous integration

on: [push, pull_request]

jobs:
  # check and build
  build-rust:
    strategy:
      fail-fast: false
      matrix:
        target:
          - bano
          - izugo
          - kono
          - nenobi
        include:
          - target: bano
            path: rust/bano
            os: linux
            host-runner: ubuntu-latest
          - target: izugo
            path: rust/izugo
            os: linux
            host-runner: ubuntu-latest
          - target: kono
            path: rust/kono
            os: linux
            host-runner: ubuntu-latest
          - target: nenobi
            path: rust/nenobi
            os: linux
            host-runner: ubuntu-latest

    runs-on: ${{ matrix.host-runner }}

    steps:
      - uses: actions/checkout@v5
      - uses: mitoma/sver-actions/setup@v2
        with:
          os: ${{ matrix.os }}
          version: v0.1.15
      # ci phase
      - name: check all
        uses: mitoma/sver-actions/exec@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          phase: check-${{ matrix.target }}-${{ matrix.os }}
          path: ${{ matrix.path }}
          command: |
            cd ${{ matrix.path }}
            cargo fmt --all -- --check
            cargo clippy -- -D warnings
            cargo build
            cargo test
          # save cache default branch only
          cache_save_enable: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
          cache_key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          cache_restore-keys: ${{ matrix.os }}-cargo-
          cache_path: |
            ~/.cargo/registry
            ~/.cargo/git
            target

  build-compiler-book:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: mitoma/sver-actions/setup@v2
        with:
          os: linux
          version: v0.1.15
      - name: check all
        uses: mitoma/sver-actions/exec@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          phase: check-compiler-book
          path: compiler-book
          command: |
            cd compiler-book
            make test
