name: Continuous integration

on: [push, pull_request]

jobs:
  # check and build
  build-rust:
    strategy:
      fail-fast: false
      matrix:
        target:
          - bano
          - izugo
          - kono
          - nenobi
        include:
          - target: bano
            path: rust/bano
            os: linux
            host-runner: ubuntu-latest
          - target: izugo
            path: rust/izugo
            os: linux
            host-runner: ubuntu-latest
          - target: kono
            path: rust/kono
            os: linux
            host-runner: ubuntu-latest
          - target: nenobi
            path: rust/nenobi
            os: linux
            host-runner: ubuntu-latest

    runs-on: ${{ matrix.host-runner }}

    steps:
      - uses: actions/checkout@v3
      - uses: mitoma/sver/.github/actions/setup_sver@v0.1.8
        with:
          os: ${{ matrix.os }}
      # ci phase
      - name: check all
        uses: mitoma/sver/.github/actions/exec_sver@v0.1.8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          phase: check-${{ matrix.target }}-${{ matrix.os }}
          path: ${{ matrix.path }}
          command: |
            cd ${{ matrix.path }}
            cargo fmt --all -- --check
            cargo clippy -- -D warnings
            cargo build
            cargo test
          cache_key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          cache_restore-keys: ${{ matrix.os }}-cargo-
          cache_path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
