name: Continuous integration

on: [push, pull_request]

jobs:
  # check and build
  build-rust:
    strategy:
      matrix:
        target:
          - rust/izugo
        include:
          - target: rust/izugo
            os: linux
            host-runner: ubuntu-latest

    runs-on: ${{ matrix.host-runner }}

    steps:
      - uses: actions/checkout@v3
      - uses: mitoma/sver/.github/actions/setup_sver@v0.1.4
        with:
          os: ${{ matrix.os }}
      - uses: mitoma/sver/.github/actions/exec_sver@v0.1.4
      # ci phase
      - name: check all
        uses: ./.github/actions/exec_sver
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          phase: check-${{ matrix.os }}
          path: ${{ matrix.target }}
          command: |
            cargo fmt --all -- --check
            cargo clippy -- -D warnings
            cargo build
            cargo test
          cache_key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          cache_restore-keys: ${{ matrix.os }}-cargo-
          cache_path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
