name: Build Docker Image for dev

on: [push]

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: mitoma/sver-actions/setup@447f10ca23a2b4026ded7c4edf24a456589a64cd # v2

      - name: build docker image
        working-directory: docker/dev
        run: |
          IMAGE_TAG="ghcr.io/mitoma/sandbox-dev:$(sver calc .)"
          echo "$GH_TOKEN" | docker login ghcr.io -u mitoma --password-stdin
          ALREADY_EXISTS=$(docker manifest inspect "$IMAGE_TAG" > /dev/null ; echo $?)

          if [ 0 -eq "$ALREADY_EXISTS" ] ;
          then
            echo "image is already exists"
            exit 0
          fi

          echo "build image. tag:${IMAGE_TAG}"
          docker build -t "$IMAGE_TAG" .
          docker push "$IMAGE_TAG"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: add tag of latest
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        working-directory: docker/dev
        run: |
          IMAGE_TAG="ghcr.io/mitoma/sandbox-dev:$(sver calc .)"
          IMAGE_TAG_LATEST="ghcr.io/mitoma/sandbox-dev:latest"
          echo "$GH_TOKEN" | docker login ghcr.io -u mitoma --password-stdin

          echo "add tag. tag:latest"
          docker pull "$IMAGE_TAG"
          docker tag "$IMAGE_TAG" "$IMAGE_TAG_LATEST"
          docker push "$IMAGE_TAG_LATEST"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
