name: Build Docker Image for dev

on: [push]

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: mitoma/sver/.github/actions/setup_sver@v0.1.12

      - name: build docker image
        working-directory: docker/dev
        run: |
          IMAGE_TAG="ghcr.io/mitoma/sandbox-dev:$(sver calc .)"
          echo $GH_TOKEN | docker login ghcr.io -u mitoma --password-stdin
          ALREADY_EXISTS=$(docker manifest inspect $IMAGE_TAG > /dev/null ; echo $?)

          if [ 0 -eq $ALREADY_EXISTS ] ;
          then
            echo "image is already exists"
            exit 0
          fi

          echo "build image. tag:${IMAGE_TAG}"
          docker build -t "$IMAGE_TAG" .
          docker push "$IMAGE_TAG"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: add tag of latest
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        working-directory: docker/dev
        run: |
          IMAGE_TAG="ghcr.io/mitoma/sandbox-dev:$(sver calc .)"
          IMAGE_TAG_LATEST="ghcr.io/mitoma/sandbox-dev:latest"
          echo $GH_TOKEN | docker login ghcr.io -u mitoma --password-stdin

          echo "add tag. tag:latest"
          docker pull "$IMAGE_TAG"
          docker tag "$IMAGE_TAG" "$IMAGE_TAG_LATEST"
          docker push "$IMAGE_TAG_LATEST"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
