name: Build Docker Image for dev

on: [push, pull_request]

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: mitoma/sver/.github/actions/setup_sver@v0.1.5

      - name: build docker image
        run: |
          echo $GH_TOKEN | docker login ghcr.io -u mitoma --password-stdin
          IMAGE_TAG="ghcr.io/mitoma/sandbox-dev:$(sver calc .)"
          ALREADY_EXISTS=$(docker manifest inspect $IMAGE_TAG > /dev/null ; echo $?)

          if $ALREADY_EXISTS ;
          then
            echo "image is already exists"
            exit 0
          fi

          echo "build image. tag:${IMAGE_TAG}"
          cd docker/dev
          docker build -t "$IMAGE_TAG" .
          docker push "$IMAGE_TAG"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
