name: Continuous integration for mitoma-org

on: [push, pull_request]

permissions:
  id-token: write
  contents: read

jobs:
  build-backend:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - uses: mitoma/sver-actions/setup@v1
      # ci phase
      - name: check all
        uses: mitoma/sver-actions/exec@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          phase: check-mitoma-org-backend
          path: mitoma-org/backend
          command: |
            cd mitoma-org/backend
            cargo fmt --all -- --check
            cargo clippy -- -D warnings
            cargo test
            cargo build --release
          # save cache default branch only
          cache_save_enable: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
          cache_key: mitoma-org-cargo-${{ hashFiles('mitoma-org/backend/Cargo.lock') }}
          cache_restore-keys: mitoma-org-cargo-
          cache_path: |
            ~/.cargo/registry
            ~/.cargo/git
            mitoma-org/backend/target
          artifact_name: mitoma-org-backend
          artifact_path: mitoma-org/backend/target/release/backend

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: mitoma/sver-actions/setup@v1
      # ci phase
      - name: check all
        uses: mitoma/sver-actions/exec@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          phase: check-mitoma-org-frontend
          path: mitoma-org/frontend
          command: |
            cd mitoma-org/frontend
            npm ci
            npm run lint
            npm run test
            npm run build
          # save cache default branch only
          cache_save_enable: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
          cache_key: mitoma-org-node-${{ hashFiles('mitoma-org/frontend/package-lock.json') }}
          cache_restore-keys: mitoma-org-node-
          cache_path: |
            ~/.npm
          artifact_name: mitoma-org-frontend
          artifact_path: mitoma-org/frontend/dist

  build-image:
    runs-on: ubuntu-latest
    needs: ["build-backend", "build-frontend"]
    steps:
      - uses: actions/checkout@v4
      - uses: mitoma/sver-actions/setup@v1
      - id: calc_version
        name: calc current version
        run: |
          backend_version="$(sver calc mitoma-org/backend)"
          echo "backend_version=${backend_version}" >> "$GITHUB_OUTPUT"
          frontend_version="$(sver calc mitoma-org/frontend)"
          echo "frontend_version=${frontend_version}" >> "$GITHUB_OUTPUT"

      - uses: actions/download-artifact@v3
        with:
          name: mitoma-org-backend-${{ steps.calc_version.outputs.backend_version }}
          path: mitoma-org/artifact/backend
        continue-on-error: true

      - uses: actions/download-artifact@v3
        with:
          name: mitoma-org-frontend-${{ steps.calc_version.outputs.frontend_version }}
          path: mitoma-org/artifact/frontend
        continue-on-error: true

      - name: "Authenticate to Google Cloud"
        id: "auth"
        uses: "google-github-actions/auth@v2.1.0"
        with:
          workload_identity_provider: ${{secrets.GCP_ID_PROVIDER }}
          service_account: ${{secrets.GCP_SERVICE_ACCOUNT }}

      - name: Configure docker for artifact registry
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: docker build
        run: |
          cd mitoma-org
          ./build.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: ["build-image"]
    steps:
      - uses: actions/checkout@v4
      - uses: mitoma/sver-actions/setup@v1
      - name: "Authenticate to Google Cloud"
        id: "auth"
        uses: "google-github-actions/auth@v2.1.0"
        with:
          workload_identity_provider: ${{secrets.GCP_ID_PROVIDER }}
          service_account: ${{secrets.GCP_SERVICE_ACCOUNT }}
      - name: Configure docker for artifact registry
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev
      - name: deploy new version
        run: |
          cd mitoma-org
          ./deploy.sh
