name: Continuous integration for mitoma-org

on: [push, pull_request]

permissions:
  id-token: write

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: mitoma/sver/.github/actions/setup_sver@v0.1.5
      # ci phase
      - name: check all
        uses: mitoma/sver/.github/actions/exec_sver@v0.1.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          phase: check-mitoma-org-backend
          path: mitoma-org/backend
          command: |
            cd mitoma-org/backend
            cargo fmt --all -- --check
            cargo clippy -- -D warnings
            cargo test
            cargo build --release
          cache_key: mitoma-org-cargo-${{ hashFiles('mitoma-org/backend/Cargo.lock') }}
          cache_restore-keys: mitoma-org-cargo-
          cache_path: |
            ~/.cargo/registry
            ~/.cargo/git
            mitoma-org/backend/target
          artifact_name: mitoma-org-backend
          artifact_path: mitoma-org/backend/target/release/backend

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: mitoma/sver/.github/actions/setup_sver@v0.1.5
      # ci phase
      - name: check all
        uses: mitoma/sver/.github/actions/exec_sver@v0.1.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          phase: check-mitoma-org-frontend
          path: mitoma-org/frontend
          command: |
            cd mitoma-org/frontend
            npm ci
            npm test
            npm run build
          cache_key: mitoma-org-node-${{ hashFiles('mitoma-org/frontend/package-lock.json') }}
          cache_restore-keys: mitoma-org-node-
          cache_path: |
            ~/.npm
          artifact_name: mitoma-org-frontend
          artifact_path: mitoma-org/frontend/build

  build-image:
    runs-on: ubuntu-latest
    needs: ["build-backend", "build-frontend"]
    steps:
      - uses: actions/checkout@v3
      - uses: mitoma/sver/.github/actions/setup_sver@v0.1.5
      - id: calc_version
        name: calc current version
        run: |
          backend_version="$(sver calc mitoma-org/backend)"
          echo "##[set-output name=backend_version;]${backend_version}"
          frontend_version="$(sver calc mitoma-org/frontend)"
          echo "##[set-output name=frontend_version;]${frontend_version}"

      - uses: actions/download-artifact@v3
        with:
          name: mitoma-org-backend-${{ steps.calc_version.outputs.backend_version }}
          path: mitoma-org/artifact/backend
        continue-on-error: true  

      - uses: actions/download-artifact@v3
        with:
          name: mitoma-org-frontend-${{ steps.calc_version.outputs.frontend_version }}
          path: mitoma-org/artifact/frontend
        continue-on-error: true  

      - name: 'Authenticate to Google Cloud'
        id: 'auth'
        uses: 'google-github-actions/auth@v0.8.0'
        with:
          workload_identity_provider: ${{secrets.GCP_ID_PROVIDER }}
          service_account: ${{secrets.GCP_SERVICE_ACCOUNT }}

      - name: Configure docker for artifact registry
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: docker build
        run: |
          cd mitoma-org
          ./build.sh
          docker images
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
